include:
  - remote: 'https://raw.githubusercontent.com/luciamo/pipelines/feat/change-node-user/gitlab/java/abstracts/gradle-application.yaml'
  - remote: 'https://raw.githubusercontent.com/luciamo/pipelines/feat/change-node-user/gitlab/java/stages/35-management/gradle.yaml'

variables:
  PREFIX: ''

.report:sonarqube:
  extends: '.gradle-application'
  cache:
    paths: # TODO: repeated code should be avoided using environment variables
      - '.gradle'
      - '.gradle-home/caches'
      - '.gradle-home/notifications'
      - '.sonar/cache'
      - 'build'
      - 'buildSrc/.gradle'
      - 'buildSrc/build'

.report:dependency-track:
  extends: '.gradle-application'
