include:
  - remote: 'https://raw.githubusercontent.com/luciamo/pipelines/feat/change-node-user/gitlab/java/abstracts/gradle-application.yaml'
  - remote: 'https://raw.githubusercontent.com/luciamo/pipelines/feat/change-node-user/gitlab/java/stages/30-tests/gradle.yaml'

variables:
  PREFIX: ''

.test:all:
  extends: '.gradle-application'

.test:build:
  extends: '.gradle-application'
  script: # TODO: some tasks as cyclonedx are running in the build and jar tasks (how to exclude?)
    - gradle build -x check -x test
  artifacts:
    paths:
      - 'build'
