include:
  - remote: 'https://raw.githubusercontent.com/luciamo/pipelines/feat/change-node-user/gitlab/global/abstracts/default-image.yaml'
  - remote: 'https://raw.githubusercontent.com/luciamo/pipelines/feat/change-node-user/gitlab/javascript/stages/10-code-check/yarn.yaml'
  - remote: 'https://raw.githubusercontent.com/luciamo/pipelines/feat/change-node-user/gitlab/javascript/stages/20-security/yarn.yaml'
  - remote: 'https://raw.githubusercontent.com/luciamo/pipelines/feat/change-node-user/gitlab/javascript/stages/30-tests/yarn.yaml'
  - remote: 'https://raw.githubusercontent.com/luciamo/pipelines/feat/change-node-user/gitlab/javascript/stages/35-management/npm-yarn.yaml'
  - remote: 'https://raw.githubusercontent.com/luciamo/pipelines/feat/change-node-user/gitlab/global/stages/40-delivery/docker.yaml'
  - remote: 'https://raw.githubusercontent.com/luciamo/pipelines/feat/change-node-user/gitlab/global/stages/40-delivery/release.yaml'

stages:
  - 'code check (style/quality)'
  - 'security (sca/sast)'
  - 'tests'
  - 'management'
  - 'delivery'
