include:
  - remote: 'https://raw.githubusercontent.com/luciamo/pipelines/feat/change-node-user/gitlab/java/abstracts/gradle.yaml'

.gradle-application:
  extends: '.gradle'
  cache:
    paths:
      - '.gradle'
      - '.gradle-home/caches'
      - '.gradle-home/notifications'
      - 'build'
      - 'buildSrc/.gradle'
      - 'buildSrc/build'
