include:
  - remote: 'https://raw.githubusercontent.com/luciamo/pipelines/feat/change-node-user/gitlab/java/abstracts/gradle-application.yaml'
  - remote: 'https://raw.githubusercontent.com/luciamo/pipelines/feat/change-node-user/gitlab/java/stages/10-code-check/gradle.yaml'

.code-check:
  extends: '.gradle-application'
